package com.codek.deliverypds.app.di

import com.codek.deliverypds.app.repository.AuthRepository
import com.codek.deliverypds.app.repository.DropboxRepository
import com.codek.deliverypds.ui.cart.viewmodel.CartViewModel
import com.codek.deliverypds.ui.home.viewmodel.HomeViewModel
import com.codek.deliverypds.ui.login.viewmodel.LoginViewModel
import com.codek.deliverypds.ui.config.viewmodel.ConfigViewModel
import com.google.firebase.auth.FirebaseAuth
import org.koin.androidx.viewmodel.dsl.viewModel
import org.koin.dsl.module

val appModule = module {

    single { AuthRepository(FirebaseAuth.getInstance()) }
    single { DropboxRepository("sl.u.AFaKjupHC6D1ZWlR_U89nbJj8dQhqfJFkeRYMqq5hK4JOpCL5s4oe0YYEvhrAS8VVzaRkwck3vIUm6hDIYcPBWlxuLmKmw2PV6cNWVLo3v4z3qKbmEfAk-rlc-dR6M1hNY89N-Ru1BgMkXn4oVMEkX1bgP3gTaMnv9MNyisTXr-28uxYUIem2_aO1g4m2wMcFHLR6ZQzOkna_GN9O0Q9OmPC0qxa2jjwQvfk8-ZKcnBPKWHZW75cOBrQDUvmqfA7wxzxRjBToibfh5u1HORFyrQkoM-MUCkEx1SIJaJj9DuOlVmgxeaTfcyYmlfdTxxpZIoR-E2WIN5JCT-LjY1F9mMZldBkyXaco42HE3lioUCAdDTEh6ozT1iQ8bTrI73r-XgDoox5kOw9tgHKrvJEiNuE0USjCPh2Atx3oSk1vkhFNxhwrVEsRI0fNmhnJ3quZ_xRLcYjyOG5b0pPVVs17bcwp19WCloHFdygJm8h2yXAnSlmJMR5l26ohgKF84BKL9M09a39BdNrrcoOpfdKAWHMRTeBIIDYQ2kn25opRVpqwLPlXXfMSshdfs4MrDAD7WTIml42BoJP59xe8Fe3ZOb5n1yb1oBEPEq5lYZvIRcfguzUX_mkFczCvnhdow0k6bmfdrRdvjivC-dwuj4ZbE_6jHWdMRwGQjgRxvUmk96saVpyotOuDSrFtVe0UG3yjga_dTLfzTR7ynOmQUN_szBU0EtpxN43SwP-zwb8AKMt2i-cxANgFleKGaxNk8dv8JYrtrgBGNfISj-wk1V3XCgizQEZ0OrFTdiHu9ObtAmvX4-5RwvnsT7nPuWRz4xMUc5ls07wxQn2xWP1CiruAT38QzcHnzBLJBedFMMigXrY6aYy4vLaELuJMP-7ohxek-_g3IN2bXSLBZe1TTwVL204XzqAjQ2ljit3I4RnZHGxt64RQGKyq7oCQEX52vJN1jAgeugHn1lNbSASqTgCuXFmAcsZ9GFUBMejI4T9oyuKaV-vMS3IdEv3UsmDdtF1_quBqqYIQwatt6WstJV5cdAak9891R1jkjXSQPGGZMkhxIRijOVMyaDnnpL8rU7yZxyIbF2IwL6zR7vqwwsuRCgqjR3NPMWB6MtTxRcPTu1ZrG3QvlNNID5kAwgoqJjqaW4j51AX1A9q4k6dvvtSoibKjyzxuQXsBSKfvxmiZ829cexth7TAtbdOo0am9WifqmrBIM2IsHenxNfn9_kAxGcUitoOh_-Ds6R8CGIU7vbh4VcD4l9NPKfneK5BPQrVtVrEqOdEcsAEVajTDkPGj6vmRa8wP4VUB43e0obpaQJx2_2w5zWChUnBxqaDM66eCiKjNTRzzwdoivo-OZD1JHq0PQDZx3ALBAwZRdtkIeTXeBeGn3N26sjenI0L7sQyUvbeYKqNpvuGztC1OFDhQPeJ-obaFygErzup9j2w6AnGz971E32nCKtjPfEmrryUzpvncPzDuyZZUDPJYAKijspo5zkiHzsQdp4E75YwZ9fndA") }

//    single { LoginViewModel(get()) }

    viewModel { LoginViewModel(get()) }

    viewModel { HomeViewModel(get()) }
    viewModel { CartViewModel() }

    viewModel { ConfigViewModel(get()) }

}